---
- hosts: '{{ hosts  }}'
  remote_user: root
  vars:
    path_file: /var/ossec/etc/ossec.conf
    key_av: "{{ key_av }}"
  tasks:

  - name: Install package ossec-agent (CentOS)
    yum: state=latest name=ossec-hids-agent update_cache=yes
    when: ansible_distribution == "CentOS"

  - name: Install repo ossec (Ubuntu 14)
    shell: "apt-key adv --fetch-keys http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key ; echo 'deb http://ossec.wazuh.com/repos/apt/ubuntu trusty main' >> /etc/apt/sources.list"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='14'

  - name: Install repo ossec (Ubuntu 16)
    shell: "apt-key adv --fetch-keys http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key ; echo 'deb http://ossec.wazuh.com/repos/apt/ubuntu xenial main' >> /etc/apt/sources.list"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='16'

  - name: Install Package
    apt: name="ossec-hids-agent" state=present
    when: ansible_distribution == "Ubuntu"

  - name: Configuration server ip
    shell: "sed -i 's#<server-ip>.*#<server-ip>172.16.84.35</server-ip>#' /var/ossec/etc/ossec.conf"

  - name: Activate KEY
    shell: "echo -e \"I\n'{{ key_av }}'\ny\n\nQ\n\" | /var/ossec/bin/manage_agent"
    when: ansible_distribution == "CentOS"
    
  - name: Activate KEY
    shell: "echo -e \"I\n'{{ key_av }}'\ny\n\nQ\n\" | /var/ossec/bin/manage_agents"
    when: ansible_distribution == "Ubuntu"
    
  - name: Cleanup config agent.conf
    shell: ":> /var/ossec/etc/shared/agent.conf"
    when: ansible_distribution == "CentOS"

  - name: reload service ossec-hids
    systemd: state=reloaded name=ossec-hids
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='7' or  ansible_distribution == "Fedora" and ansible_distribution_major_version =='24'

  - name: reload service ossec-hids
    service: state=reloaded name=ossec-hids
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6' or ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='14'

  - name: reload service ossec-hids
    systemd: state=reloaded name=ossec.service
    when: ansible_distribution == "Ubuntu"
